### ISSUE TITLE
Redesign user management

### ISSUE THREAD

**Issue by BjoernLange** [fspiekermann/rusty_pizza#16]
We should move user management out of the order model. A collection of users is required with each user having a unique ID. The user ID is then used to identify the user and associate `Order`s and `Meal`s.

# Acceptance criteria
- Users have a unique ID
- User IDs are used instead of `Rc<User>` in the order model
- Unit tests exist and pass
- Manager of `Order` gets a `Meals` per defualt

**Comment by fspiekermann** [comment]
The manager of an `Order` should get a `Meals` per default, so he can take part at this order without adding him in a second step.
