### ISSUE TITLE
Extend Money type to compare it

### ISSUE THREAD

**Issue by fspiekermann** [fspiekermann/rusty_pizza#18]
At the moment we are not able to compare two money types directly. The workaround to compare the total cents is not the loviest way. Overload the `std::cmp::PartialOrd::*` Comparison Operators once for `Money` type would simplify future work

# Acceptance criteria

- `>` | Greater than | `std::cmp::PartialOrd::gt` is added to `Money` type
- `<` | Less than | `std::cmp::PartialOrd::lt` is added to `Money` type
- `>=` | Greater than or equal to | `std::cmp::PartialOrd::ge` is added to `Money` type
- `<=` | Less than or equal to | `std::cmp::PartialOrd::le` is added to `Money` type
- Unit tests exist and pass

**Comment by fspiekermann** [comment]
#23 adds PartialOrd to `Money`, which solves this issue. I don´t think we need to test ist, since it is rust function.

**Comment by BjoernLange** [comment]
I agree.
